<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>FastCsvKit</PackageId>
    <Title>Fast CsvKit</Title>
    <Version>1.0.0</Version>
    <Authors>Andrei Xavier</Authors>
    <Company>Andrei Xavier</Company>
    <Description>Fast and lightweight CSV library for .NET</Description>
    <Copyright></Copyright>
  </PropertyGroup>

</Project>
